name: activity2 php 
become: true
hosts: all
tasks:
  - name: install apache and php packages
    ansible.builtin.apt:
      - name: 
          - apache
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
        update_cache: true
  - name: copy php files  
    ansible.builtin.copy:
       src: info.php
       dest: /var/www/html/info.php